### ISSUE TITLE
Fails Training in Bedrock UI

### ISSUE THREAD

**Issue by raminetinati** [basisai/churn_prediction#47]
Looks like there's been an upgrade to the package, and IPython has been removed. See training Log:

Collecting six<2.0,>=1.14.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting thrift>=0.11.0
  Downloading thrift-0.13.0.tar.gz (59 kB)
Collecting tqdm>4.25.0
  Downloading tqdm-4.56.0-py2.py3-none-any.whl (72 kB)
Collecting urllib3<1.27,>=1.25.4
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting cloudpickle
  Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting fluent-logger
  Downloading fluent_logger-0.9.6-py2.py3-none-any.whl (12 kB)
Collecting msgpack<1.0.0
  Downloading msgpack-0.6.2.tar.gz (119 kB)
Collecting matplotlib
  Downloading matplotlib-3.3.3-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp38-cp38-manylinux1_x86_64.whl (1.2 MB)
Collecting pillow>=6.2.0
  Downloading Pillow-8.1.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting prometheus-client
  Downloading prometheus_client-0.9.0-py2.py3-none-any.whl (53 kB)
Building wheels for collected packages: fastparquet, pyspark, shap, thrift, msgpack
  Building wheel for fastparquet (setup.py): started
  Building wheel for fastparquet (setup.py): finished with status 'done'
  Created wheel for fastparquet: filename=fastparquet-0.3.3-cp38-cp38-linux_x86_64.whl size=288634 sha256=0fa38d5433300b804843c08b89af390fcf5422633da77ff7d22a5d4359066f42
  Stored in directory: /root/.cache/pip/wheels/ab/e4/8a/5bf9e2dfbe90b06d3aa6f0fba3cf2f5e9514ce20d7f73acdd4
  Building wheel for pyspark (setup.py): started
  Building wheel for pyspark (setup.py): finished with status 'done'
  Created wheel for pyspark: filename=pyspark-2.4.4-py2.py3-none-any.whl size=216130388 sha256=2fe65d6697e76e73fcec2094b43b545c450a756a27e8d977afbfcdbef34c3262
  Stored in directory: /root/.cache/pip/wheels/2f/68/df/a094fd6e3c269067f562832302ed538586a86411467ebdf69b
  Building wheel for shap (setup.py): started
  Building wheel for shap (setup.py): finished with status 'done'
  Created wheel for shap: filename=shap-0.38.1-cp38-cp38-linux_x86_64.whl size=540779 sha256=ccec5b87810d894f39d6d4f6df9c887e1dcebccecf12e28b180e3126afef2fd9
  Stored in directory: /root/.cache/pip/wheels/87/7c/3f/1012132e5a8db6b4e125e64be0fd96f581803e101b0403c65f
  Building wheel for thrift (setup.py): started
  Building wheel for thrift (setup.py): finished with status 'done'
  Created wheel for thrift: filename=thrift-0.13.0-cp38-cp38-linux_x86_64.whl size=493769 sha256=5939ae9db641120eec9b879ae116a4ecc753440da41addb3f0eacae65ccdf2b3
  Stored in directory: /root/.cache/pip/wheels/0a/52/7e/8054b57725b8f2b9ddbaacb81b271b939681cc03f8231e6ebc
  Building wheel for msgpack (setup.py): started
  Building wheel for msgpack (setup.py): finished with status 'done'
  Created wheel for msgpack: filename=msgpack-0.6.2-cp38-cp38-linux_x86_64.whl size=304867 sha256=1432480d5d641d9d60e05d5006fb92de73269bbf0f82204c3ea07143ecceae12
  Stored in directory: /root/.cache/pip/wheels/5d/f2/04/0d19c10080b996bef17c908a6243e6e65d8da1a4094a3f604d
Successfully built fastparquet pyspark shap thrift msgpack
Installing collected packages: six, numpy, scipy, pytz, python-dateutil, pyparsing, pillow, llvmlite, kiwisolver, joblib, cycler, urllib3, tqdm, slicer, scikit-learn, pandas, numba, matplotlib, idna, cloudpickle, chardet, certifi, shap, requests, msgpack, jmespath, aif360, thrift, py4j, prometheus-client, fsspec, fluent-logger, botocore, bdrk, s3fs, pyspark, lightgbm, fastparquet
Successfully installed aif360-0.3.0 bdrk-0.4.2 botocore-1.19.58 certifi-2020.12.5 chardet-4.0.0 cloudpickle-1.6.0 cycler-0.10.0 fastparquet-0.3.3 fluent-logger-0.9.6 fsspec-0.8.5 idna-2.10 jmespath-0.10.0 joblib-1.0.0 kiwisolver-1.3.1 lightgbm-2.3.1 llvmlite-0.35.0 matplotlib-3.3.3 msgpack-0.6.2 numba-0.52.0 numpy-1.18.4 pandas-1.0.3 pillow-8.1.0 prometheus-client-0.9.0 py4j-0.10.7 pyparsing-2.4.7 pyspark-2.4.4 python-dateutil-2.8.1 pytz-2020.5 requests-2.25.1 s3fs-0.4.2 scikit-learn-0.22.1 scipy-1.6.0 shap-0.38.1 six-1.15.0 slicer-0.0.7 thrift-0.13.0 tqdm-4.56.0 urllib3-1.26.2
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from bedrock_client.bedrock.analyzer.model_analyzer import ModelAnalyzer
  File "/usr/local/lib/python3.8/site-packages/bedrock_client/bedrock/analyzer/__init__.py", line 3, in <module>
    from .model_analyzer import ModelAnalyzer
  File "/usr/local/lib/python3.8/site-packages/bedrock_client/bedrock/analyzer/model_analyzer.py", line 18, in <module>
    from . import explainability as exp
  File "/usr/local/lib/python3.8/site-packages/bedrock_client/bedrock/analyzer/explainability.py", line 5, in <module>
    import shap
  File "/usr/local/lib/python3.8/site-packages/shap/__init__.py", line 38, in <module>
    from .plots._beeswarm import summary_legacy as summary_plot
  File "/usr/local/lib/python3.8/site-packages/shap/plots/__init__.py", line 8, in <module>
    from ._image import image, image_to_text
  File "/usr/local/lib/python3.8/site-packages/shap/plots/_image.py", line 15, in <module>
    from IPython.core.display import display, HTML
ModuleNotFoundError: No module named 'IPython'
[BDRK] Log stream closed

**Comment by kesamet** [comment]
The requirements files have been updated: the package "bdrk" has been bumped up to 0.6.0. You can try again.
